### ISSUE TITLE
A couple of questions

### ISSUE THREAD

**Issue by gamer321lol** [orcfoss/Rboxlo#117]
What addon thingys (the things that u get to install in setup) do u need for visual studio 2019? 
Does it support community edition?
What did you use to make the logo?
i am confused

**Comment by lightbulblighter** [comment]
1. I'm not sure what you mean by "add-on" thingies; you just need Visual Studio 2019.
2. Rboxlo is able to be built using any edition of Visual Studio 2019.
3. paint.net
